version: "3"
services:
    jupyter:
        build: ./libraries
        container_name: jupyter
        runtime: nvidia
        volumes:
            - ./notebook/:/home/jovyan/notebook
        ports:
            - 80:8888
        environment:
            NVIDIA_VISIBLE_DEVICES: all
            NVIDIA_DRIVER_CAPABILITIES: all
