version: "3"
services:
    jupyter:
        build: ./libraries
        volumes:
            - ./notebook/:/tmp/working
        ports:
            - 80:8888
        command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser